-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql212.infinityfree.com
-- Generation Time: Oct 15, 2024 at 06:27 PM
-- Server version: 10.6.19-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `if0_37514017_project`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `c_name` varchar(255) DEFAULT NULL,
  `c_img` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `c_name`, `c_img`) VALUES
(3, 'Kitchens', 'IMG-20241015-WA0006.jpg'),
(4, 'Wardrobe', 'IMG-20241015-WA0005.jpg'),
(5, 'Modern Doors', 'IMG-20241015-WA0011.jpg'),
(6, 'Dressing Tables', 'IMG-20241015-WA0010.jpg'),
(7, 'Wood Flooring', 'WhatsApp Image 2024-10-15 at 19.55.04_e2bce767.jpg'),
(8, 'Wood Interior', 'WhatsApp Image 2024-10-15 at 16.46.10_3f7ba515.jpg'),
(9, 'Office Works', 'IMG-20241015-WA0004.jpg'),
(10, 'Dining Tables', 'IMG-20241015-WA0012.jpg'),
(11, 'Media Wall', 'IMG-20241015-WA0007.jpg'),
(12, 'Bedroom Sets', 'IMG-20241015-WA0009.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `p_name` varchar(255) DEFAULT NULL,
  `p_img` varchar(255) DEFAULT NULL,
  `p_category` varchar(255) DEFAULT NULL,
  `p_description` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `p_name`, `p_img`, `p_category`, `p_description`) VALUES
(11, 'Luxurious Modern Kitchen Island', 'WhatsApp Image 2024-10-04 at 9.25.49 AM.jpeg', 'Kitchens', 'Elevate your kitchen space with this stunning modern kitchen island. Crafted with high-quality materials and featuring a sleek, minimalist design, this island is both functional and visually appealing. The spacious countertop provides ample room for meal prep, cooking, and dining. The built-in storage compartments offer plenty of space for organizing kitchen essentials. The island\'s elegant lighting creates a warm and inviting atmosphere, perfect for entertaining guests or enjoying a quiet meal. This luxurious kitchen island is a must-have for any discerning homeowner seeking to create a sophisticated and stylish kitchen.'),
(12, 'Sleek L-Shaped Modern Kitchen', 'WhatsApp Image 2024-10-04 at 9.25.48 AM.jpeg', 'Kitchens', 'This modern L-shaped kitchen is a masterpiece of design and functionality. The sleek, minimalist aesthetic is complemented by warm wood accents and stunning marble flooring. The spacious layout provides ample room for cooking, dining, and socializing. The abundance of storage space ensures that your kitchen remains organized and clutter-free. The high-quality appliances and fixtures add to the overall luxury and sophistication of this kitchen. Whether you\'re a professional chef or simply enjoy cooking at home, this L-shaped kitchen is the perfect space to create culinary masterpieces.'),
(13, 'Modern Industrial Kitchen with Island', 'WhatsApp Image 2024-10-04 at 9.25.46 AM (1).jpeg', 'Kitchens', 'This modern industrial kitchen is a perfect blend of style and functionality. The sleek, dark cabinetry creates a dramatic and sophisticated atmosphere, while the warm wood island adds a touch of natural warmth. The open-plan layout allows for seamless flow between the kitchen and living areas. The island features a built-in wine rack and storage compartments, providing both style and practicality. The high-quality appliances and fixtures complete the modern industrial look. This kitchen is ideal for those seeking a stylish and functional space to cook, entertain, and relax.'),
(14, 'Luxurious Modern Kitchen Island', 'WhatsApp Image 2024-10-04 at 9.25.46 AM.jpeg', 'Kitchens', 'Elevate your kitchen space with this stunning modern kitchen island. Crafted with high-quality materials and featuring a sleek, minimalist design, this island is both functional and visually appealing. The spacious countertop provides ample room for meal prep, cooking, and dining. The built-in storage compartments offer plenty of space for organizing kitchen essentials. The island\'s elegant lighting creates a warm and inviting atmosphere, perfect for entertaining guests or enjoying a quiet meal. This luxurious kitchen island is a must-have for any discerning homeowner seeking to create a sophisticated and stylish kitchen.'),
(15, 'Modern Industrial L-Shaped Kitchen', 'WhatsApp Image 2024-10-04 at 9.25.45 AM (2).jpeg', 'Kitchens', 'This modern L-shaped kitchen is a perfect blend of industrial style and contemporary design. The sleek black cabinetry and textured accents create a dramatic and sophisticated atmosphere, while the warm wood elements add a touch of natural warmth. The L-shaped layout provides ample space for cooking, dining, and socializing. The island features built-in storage compartments and a stylish pendant light, adding both functionality and visual appeal. This kitchen is ideal for those seeking a stylish and functional space to cook, entertain, and relax.'),
(16, 'Sleek Modern Kitchen with Island', 'WhatsApp Image 2024-10-04 at 9.25.45 AM.jpeg', 'Kitchens', 'This modern kitchen is a perfect blend of style and functionality. The sleek black cabinetry creates a dramatic and sophisticated atmosphere, while the white countertop adds a touch of brightness. The large island provides ample space for cooking, dining, and socializing. The recessed lighting and pendant lights create a warm and inviting atmosphere. The high-quality appliances and fixtures complete the modern look. This kitchen is ideal for those seeking a stylish and functional space to cook, entertain, and relax.'),
(17, 'Glamorous Vanity Set with LED Mirror', 'WhatsApp Image 2024-10-04 at 10.33.37 AM (1).jpeg', 'Dressing Tables', 'This elegant vanity set is the perfect addition to any modern bedroom. The sleek white finish and gold accents create a luxurious and sophisticated look. The vanity features a spacious countertop with multiple drawers for storage, keeping your makeup and accessories organized. The highlight of the set is the stunning LED mirror with an irregular shape that adds a touch of glamour. The adjustable lighting provides optimal illumination for flawless makeup application. The included vanity chair completes the set, offering a comfortable and stylish place to sit while getting ready. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(18, 'Modern White Vanity Table with 9 Drawers and LED Mirror', 'WhatsApp Image 2024-10-04 at 10.33.37 AM.jpeg', 'Dressing Tables', 'This elegant vanity set is a perfect addition to any bedroom or dressing room. The sleek white design and gold hardware create a sophisticated and modern look. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as nine drawers for ample storage. The large, rectangular mirror is illuminated by bright LED lights, providing the perfect lighting for applying makeup.   The included stool adds a touch of comfort and style. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(19, 'Hollywood Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.33.36 AM (1).jpeg', 'Dressing Tables', 'This stylish vanity set is a perfect addition to any bedroom or dressing room. The sleek white design and modern lines create a chic and contemporary look. The vanity features a spacious tabletop with ample space for makeup and accessories. The highlight of the set is the large, illuminated mirror with Hollywood-style LED lights that provide the perfect lighting for applying makeup. The vanity also includes a built-in shelf unit for storing cosmetics, skincare products, and other essentials. The included stool offers a comfortable place to sit while getting ready. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(20, 'Modern White Vanity Set with Double Mirrors and Storage', 'WhatsApp Image 2024-10-04 at 10.33.36 AM.jpeg', 'Dressing Tables', 'This elegant vanity set is a perfect addition to any bedroom or dressing room. The sleek white design and gold hardware create a sophisticated and modern look. The vanity features a spacious tabletop with ample space for makeup and accessories. The highlight of the set is the large, double mirror with LED lights that provide the perfect lighting for applying makeup. The vanity also includes a built-in shelf unit for storing cosmetics, skincare products, and other essentials. The included stool offers a comfortable place to sit while getting ready. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(21, 'Modern Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.57 AM (2).jpeg', 'Dressing Tables', 'This sleek vanity set is a perfect addition to any bedroom or dressing room. The black finish creates a sophisticated and modern look, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as multiple drawers for storage. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in shelf unit offers additional storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(22, 'Modern Black Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.57 AM (1).jpeg', 'Dressing Tables', 'This sleek vanity set is a perfect addition to any bedroom or dressing room. The black finish creates a sophisticated and modern look, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as multiple drawers for storage. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in shelf unit offers additional storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(23, 'Hollywood Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.57 AM.jpeg', 'Dressing Tables', 'This stylish vanity set is a perfect addition to any bedroom or dressing room. The sleek black finish creates a sophisticated and modern look, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as multiple drawers for storage. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in shelf unit offers additional storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(24, 'Glamorous Vanity Set with LED Mirror and Gold Accents', 'WhatsApp Image 2024-10-04 at 10.32.56 AM.jpeg', 'Dressing Tables', 'This elegant vanity set is a perfect addition to any modern bedroom. The sleek black finish and gold accents create a luxurious and sophisticated look. The vanity features a spacious countertop with ample space for makeup and accessories. The LED mirror with a stylish frame provides the perfect lighting for flawless makeup application. The included vanity chair with a gold metal frame adds a touch of glamour and comfort. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(25, 'Modern Black Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.54 AM.jpeg', 'Dressing Tables', 'This sleek vanity set is a perfect addition to any bedroom or dressing room. The black finish creates a sophisticated and modern look, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as multiple drawers for storage. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in shelf unit offers additional storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(26, 'Hollywood Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.53 AM.jpeg', 'Dressing Tables', 'This stylish vanity set is a perfect addition to any bedroom or dressing room. The white finish creates a bright and airy atmosphere, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as multiple drawers for storage. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in shelving units on either side offer additional storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(27, 'Professional Makeup Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.52 AM (1).jpeg', 'Dressing Tables', 'This large and luxurious vanity set is perfect for makeup artists, beauty enthusiasts, or anyone who needs ample space for their beauty routine. The set features a spacious vanity table with multiple drawers for storage, a large illuminated mirror with Hollywood-style LED lights, and two additional side units with shelves for organizing products. The vanity is designed to provide ample space for all your makeup and beauty tools, making it a perfect workspace for professionals and amateurs alike. This vanity set is a must-have for anyone who wants to create a stylish and functional beauty station.'),
(28, 'Luxurious White Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.52 AM.jpeg', 'Dressing Tables', 'This elegant vanity set is a perfect addition to any bedroom or dressing room. The sleek white finish and crystal accents create a luxurious and sophisticated look. The vanity features a spacious countertop with ample space for makeup and accessories. The large, illuminated mirror provides the perfect lighting for flawless makeup application. The vanity also includes multiple drawers for storage, keeping your beauty essentials organized. The included vanity stool adds a touch of comfort and style. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(29, 'Hollywood Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.51 AM.jpeg', 'Dressing Tables', 'This stylish vanity set is a perfect addition to any bedroom or dressing room. The white finish creates a bright and airy atmosphere, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in compartments and drawers offer plenty of storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(30, 'Modern Vanity Set with LED Lights, Storage, and Charging Station', 'WhatsApp Image 2024-10-04 at 10.32.50 AM (2).jpeg', 'Dressing Tables', 'This sleek vanity set is a perfect addition to any bedroom or dressing room. The white finish creates a bright and airy atmosphere, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories, as well as multiple drawers for storage. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in shelving units offer additional storage for cosmetics, skincare products, and other essentials. The built-in charging station is a convenient feature for keeping your devices powered up. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(31, 'Modern Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.50 AM (1).jpeg', 'Dressing Tables', 'This stylish vanity set is a perfect addition to any bedroom or dressing room. The white finish creates a bright and airy atmosphere, while the LED lights add a touch of glamour. The vanity features a spacious tabletop with ample space for makeup and accessories. The included stool provides a comfortable place to sit while getting ready. The vanity\'s built-in compartments and drawers offer plenty of storage for cosmetics, skincare products, and other essentials. This vanity set is a must-have for anyone who wants to create a stylish and functional dressing area.'),
(32, 'Versatile Dressing Table with Storage', 'WhatsApp Image 2024-10-04 at 10.32.50 AM.jpeg', 'Dressing Tables', 'This multifunctional dressing table is perfect for any bedroom or home office. The sleek white design and natural wood accents create a stylish and modern look. The spacious tabletop provides ample room for a laptop, makeup, or other essentials. The built-in drawers offer plenty of storage space for organizing your belongings. The included stool provides a comfortable place to sit while working or getting ready. This dressing table is a versatile piece of furniture that can be used in various ways to suit your needs.'),
(33, 'Corner Vanity Set with LED Lights and Storage', 'WhatsApp Image 2024-10-04 at 10.32.49 AM.jpeg', 'Dressing Tables', 'This stylish corner vanity set is a perfect space-saving solution for any bedroom or dressing room. The sleek white design and LED lights create a modern and glamorous look. The vanity features a spacious tabletop with ample space for makeup and accessories. The built-in shelving units and drawers offer plenty of storage for organizing your beauty essentials. The included stool provides a comfortable place to sit while getting ready. This corner vanity set is a great way to maximize your space and create a stylish and functional dressing area.'),
(34, 'Modern Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.29 AM.jpeg', 'Modern Doors', 'Make a statement with this stunning modern double-door entryway. The rich wood tones and geometric design create a sophisticated and inviting entrance. The sleek door handles and recessed lighting add a touch of luxury. The accompanying planter boxes and wall sconces complete the elegant look. This entryway is perfect for any homeowner looking to create a lasting impression.'),
(35, 'Contemporary Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.28 AM (1).jpeg', 'Modern Doors', 'This modern double-door entryway features a sleek design with geometric accents and large glass sidelights. The rich wood tones and clean lines create a sophisticated and inviting entrance. The recessed lighting and modern door hardware add a touch of elegance. This entryway is perfect for any homeowner looking to create a stylish and functional entrance to their home.'),
(36, 'Modern Minimalist Entryway', 'WhatsApp Image 2024-10-04 at 10.18.28 AM.jpeg', 'Modern Doors', 'This sleek and modern entryway features a minimalist design with clean lines and a neutral color palette. The black door with vertical wooden slats adds a touch of texture and warmth. The recessed lighting and wall sconces create a welcoming atmosphere. The potted plants and greenery add a natural element to the space. This entryway is perfect for homeowners who appreciate a modern and minimalist aesthetic.'),
(37, 'Modern Geometric Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.27 AM (1).jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern geometric design with contrasting wood and black accents. The large glass sidelights allow for natural light to enter the home. The sleek door handle and recessed lighting add a touch of elegance. This entryway is perfect for homeowners who appreciate a contemporary and stylish look.'),
(38, 'Contemporary Brushed Gold Door Handles', 'WhatsApp Image 2024-10-04 at 10.18.27 AM.jpeg', 'Modern Doors', 'These sleek and modern brushed gold door handles are the perfect finishing touch for any contemporary home. The clean lines and minimalist design add a touch of elegance to any door. The high-quality brushed gold finish creates a warm and inviting atmosphere. These door handles are available in various sizes and styles to match your door design.'),
(39, 'Modern Black Single-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.26 AM (1).jpeg', 'Modern Doors', 'This sleek and modern single-door entryway features a black finish with horizontal slats for a contemporary look. The brushed gold door handle adds a touch of elegance. The surrounding wood cladding and potted plants create a warm and inviting atmosphere. This entryway is perfect for homeowners who appreciate a minimalist and modern design.'),
(40, 'Modern Minimalist Entryway', 'WhatsApp Image 2024-10-04 at 10.18.26 AM.jpeg', 'Modern Doors', 'This sleek and modern entryway features a black door with a vertical wooden accent. The minimalist design and clean lines create a sophisticated and inviting entrance. The recessed lighting and potted plants add a touch of warmth and greenery. This entryway is perfect for homeowners who appreciate a modern and minimalist aesthetic.'),
(41, 'Modern Black Single-Door Entryway with Stone Accents', 'WhatsApp Image 2024-10-04 at 10.18.25 AM (1).jpeg', 'Modern Doors', 'This stylish entryway features a modern black door with a sleek vertical handle. The surrounding stone cladding adds a natural and textured element to the design. The recessed lighting and overhang create a welcoming atmosphere. This entryway is perfect for homeowners who appreciate a modern and minimalist aesthetic with a touch of warmth.'),
(42, 'Modern Double-Door Entryway with Stone Accents', 'WhatsApp Image 2024-10-04 at 10.18.25 AM.jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern design with contrasting black frames and a warm wood door. The surrounding stone cladding adds a natural and textured element to the design. The recessed lighting and overhang create a welcoming atmosphere. This entryway is perfect for homeowners who appreciate a modern and minimalist aesthetic with a touch of warmth.'),
(43, 'Modern Wood and Stone Entryway', 'WhatsApp Image 2024-10-04 at 10.18.24 AM (1).jpeg', 'Modern Doors', 'This stylish entryway features a modern blend of wood and stone elements. The warm wood door and cladding create a natural and inviting atmosphere, while the stone accents add a touch of sophistication. The recessed lighting and hanging lanterns provide ample illumination. The front porch with wooden steps and planter boxes creates a welcoming entrance. This entryway is perfect for homeowners who appreciate a modern and rustic aesthetic.'),
(44, 'Modern Geometric Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.24 AM.jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern geometric design with contrasting black frames and a warm wood door. The large glass sidelights allow for ample natural light. The sleek door handle and recessed lighting add a touch of elegance. This entryway is perfect for homeowners who appreciate a contemporary and stylish look.'),
(45, 'Modern Wood and Stone Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.23 AM.jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern blend of wood and stone elements. The warm wood door and cladding create a natural and inviting atmosphere, while the stone accents add a touch of sophistication. The recessed lighting and hanging lanterns provide ample illumination. The front porch with wooden steps and planter boxes creates a welcoming entrance. This entryway is perfect for homeowners who appreciate a modern and rustic aesthetic.'),
(46, 'Modern Curved Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.22 AM (1).jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern curved design with a circular motif. The black metal door with a geometric pattern creates a striking and eye-catching entrance. The surrounding stone cladding adds a natural and textured element to the design. The recessed lighting and wall sconces provide ample illumination. The potted plants and greenery add a touch of warmth and life. This entryway is perfect for homeowners who appreciate a bold and modern aesthetic.'),
(47, 'Modern Geometric Double-Door Entryway', 'WhatsApp Image 2024-10-04 at 10.18.22 AM.jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern geometric design with contrasting wood and black panels. The intricate patterns and textures create a visually striking entrance. The gold door handles add a touch of luxury and sophistication. This entryway is perfect for homeowners who appreciate a contemporary and stylish look.'),
(48, 'Modern Double-Door Entryway with Vertical Slats', 'WhatsApp Image 2024-10-04 at 10.18.21 AM (1).jpeg', 'Modern Doors', 'This stylish double-door entryway features a modern design with vertical wooden slats for a contemporary look. The rich brown wood tone creates a warm and inviting atmosphere. The unique fan-shaped door handles add a touch of elegance. The surrounding stone cladding and potted plants complete the sophisticated look. This entryway is perfect for homeowners who appreciate a modern and minimalist aesthetic.'),
(49, 'Modern Double-Door Entryway with Wood and Black Accents', 'WhatsApp Image 2024-10-04 at 10.18.21 AM.jpeg', 'Kitchens', 'This stylish double-door entryway features a modern design with contrasting wood and black panels. The rich wood tones and sleek black accents create a sophisticated and inviting entrance. The recessed lighting and wall sconces provide ample illumination. The potted plants and greenery add a touch of warmth and life. This entryway is perfect for homeowners who appreciate a modern and minimalist aesthetic.'),
(50, 'Modern Geometric Wooden Door', 'WhatsApp Image 2024-10-04 at 10.18.20 AM (2).jpeg', 'Modern Doors', 'This stylish wooden door features a modern geometric design with contrasting wood panels. The intricate patterns and textures create a visually striking entrance. The rich wood tone adds warmth and natural beauty. This door is perfect for homeowners who appreciate a contemporary and stylish look.'),
(51, 'Modern Vertical Slatted Wooden Door', 'WhatsApp Image 2024-10-04 at 10.18.20 AM (1).jpeg', 'Modern Doors', 'This stylish wooden door features a modern design with vertical slats for a contemporary look. The rich wood tone adds warmth and natural beauty. The sleek gold door handles create a luxurious and sophisticated feel. This door is perfect for homeowners who appreciate a modern and minimalist aesthetic.'),
(52, 'Modern Vertical Slatted Wooden Door', 'WhatsApp Image 2024-10-04 at 10.18.20 AM.jpeg', 'Modern Doors', 'This stylish wooden door features a modern design with vertical slats for a contemporary look. The rich wood tone adds warmth and natural beauty. The glass panels provide a touch of elegance and allow for natural light to enter the room. This door is perfect for homeowners who appreciate a modern and minimalist aesthetic.'),
(53, 'Modern Vertical Slatted Wooden Door', 'WhatsApp Image 2024-10-04 at 10.18.19 AM (1).jpeg', 'Modern Doors', 'This stylish wooden door features a modern design with vertical slats for a contemporary look. The rich wood tone adds warmth and natural beauty. The black sidelights and door frame create a sleek and minimalist aesthetic. The silver door handle adds a touch of elegance. This door is perfect for homeowners who appreciate a modern and minimalist design.'),
(54, 'Modern Geometric Wooden Door', 'WhatsApp Image 2024-10-04 at 10.18.19 AM.jpeg', 'Modern Doors', 'This stylish wooden door features a modern geometric design with contrasting wood panels. The intricate patterns and textures create a visually striking entrance. The rich wood tone adds warmth and natural beauty. This door is perfect for homeowners who appreciate a contemporary and stylish look.'),
(55, 'Modern Wooden Security Door', 'WhatsApp Image 2024-10-04 at 10.18.17 AM.jpeg', 'Modern Doors', 'This sturdy and secure wooden door features a modern design with horizontal panels. The rich mahogany finish adds a touch of elegance, while the reinforced steel core provides exceptional strength and security. The door includes a high-quality lock and peephole for added safety. This door is perfect for homeowners who value both style and security.'),
(56, 'Modern Wooden Door with Vertical Slats and Glass Panel', 'WhatsApp Image 2024-10-04 at 10.18.16 AM.jpeg', 'Modern Doors', 'This stylish wooden door features a modern design with vertical slats for a contemporary look. The rich wood tone adds warmth and natural beauty. The glass panel provides a touch of elegance and allows for natural light to enter the room. The sleek door handle completes the modern aesthetic. This door is perfect for homeowners who appreciate a minimalist and functional design.'),
(57, 'Modern Wooden Door with Intricate Carving', 'WhatsApp Image 2024-10-04 at 10.18.15 AM (2).jpeg', 'Modern Doors', 'This stylish wooden door features a modern design with intricate carvings that add a touch of elegance and personality. The rich brown finish creates a warm and inviting atmosphere. The door includes a high-quality lock and handle for added security. This door is perfect for homeowners who appreciate a unique and sophisticated look.'),
(58, 'Modern Minimalist Walnut Door', 'WhatsApp Image 2024-10-04 at 10.18.15 AM.jpeg', 'Modern Doors', 'his sleek and sophisticated modern door features a clean, minimalist design with horizontal walnut slats set against a rich, dark frame. The natural grain of the walnut adds a touch of warmth and character to the door, while the clean lines and minimalist aesthetic create a contemporary and elegant look. The door is perfect for any modern or contemporary interior and can be used as an interior door or a front door.'),
(59, 'Contemporary Entryway Storage System', 'WhatsApp Image 2024-10-04 at 10.05.43 AM (1).jpeg', 'Wardrobe', 'This stylish and functional entryway storage system combines modern design with ample storage space. The unit features a wardrobe with sliding doors, a built-in shoe rack, and open shelves for storing accessories. The frosted glass doors add a touch of elegance and allow for easy visibility of your belongings. The warm wood tones and neutral colors create a welcoming and inviting atmosphere.'),
(60, 'Modern Sliding Door Wardrobe', 'WhatsApp Image 2024-10-04 at 10.05.43 AM.jpeg', 'Wardrobe', 'This sleek and functional wardrobe features a modern design with sliding doors that save space and provide easy access to your clothes. The combination of frosted glass and solid panels adds a touch of elegance and visual interest. The interior is thoughtfully designed with shelves, drawers, and hanging rods to accommodate all your clothing and accessories. The built-in LED lighting provides a bright and illuminating interior.'),
(61, 'Luxurious Modern Wardrobe with Glass Doors', 'WhatsApp Image 2024-10-04 at 10.05.41 AM (2).jpeg', 'Wardrobe', 'This exquisite wardrobe combines modern design with a touch of luxury. The sleek gray finish is complemented by elegant gold accents and glass doors that showcase your belongings. The interior features ample storage space with shelves, drawers, and hanging rods. The built-in LED lighting adds a touch of glamour and illuminates your wardrobe.'),
(62, 'Modern Walk-In Closet with Integrated Storage', 'WhatsApp Image 2024-10-04 at 10.05.41 AM (1).jpeg', 'Wardrobe', 'This spacious and functional walk-in closet features a modern design with clean lines and ample storage space. The combination of gray cabinets and warm wood accents creates a stylish and inviting atmosphere. The closet is equipped with shelves, drawers, hanging rods, and a built-in vanity area. The integrated lighting provides excellent visibility and adds a touch of luxury.'),
(63, 'Sleek Modern Sliding Door Wardrobe', 'WhatsApp Image 2024-10-04 at 10.05.41 AM.jpeg', 'Wardrobe', 'This contemporary wardrobe features a minimalist design with sliding doors that save space and provide easy access to your clothing. The neutral gray finish is complemented by subtle gold accents for a touch of sophistication. The interior is thoughtfully designed with shelves, drawers, and hanging rods to accommodate all your belongings.'),
(64, 'Multifunctional Entryway Storage Unit', 'WhatsApp Image 2024-10-04 at 10.05.40 AM.jpeg', 'Wardrobe', 'This versatile entryway storage unit combines a wardrobe, a built-in bench, and open shelves for a functional and stylish solution. The sleek gray finish creates a modern and minimalist look, while the warm wood accents add a touch of natural warmth. The unit is perfect for organizing your belongings and providing a comfortable place to sit and take off your shoes.'),
(65, 'Modern Entryway Coat Rack with Storage', 'WhatsApp Image 2024-10-04 at 10.05.39 AM.jpeg', 'Wardrobe', 'This sleek and functional entryway coat rack combines a modern design with practical storage solutions. The dark cabinet with a wood accent provides ample storage for coats, shoes, and accessories. The built-in bench offers a comfortable place to sit and take off your shoes, while the hooks above are perfect for hanging coats, hats, and bags. The integrated lighting adds a touch of sophistication and illuminates the space.'),
(66, 'Modern Walk-In Closet with Built-In Seating', 'WhatsApp Image 2024-10-04 at 10.05.38 AM.jpeg', 'Wardrobe', 'This luxurious walk-in closet features a modern design with ample storage space and a built-in seating area for added comfort. The sleek gray cabinets and warm wood accents create a stylish and inviting atmosphere. The closet is equipped with shelves, drawers, hanging rods, and a full-length mirror. The integrated lighting provides excellent visibility and adds a touch of sophistication.'),
(67, 'Modern Sliding Door Wardrobe with Integrated Storage', 'WhatsApp Image 2024-10-04 at 10.05.37 AM.jpeg', 'Wardrobe', 'This sleek and functional wardrobe features a modern design with sliding doors that save space and provide easy access to your clothing. The combination of gray and white panels adds a touch of visual interest, while the integrated storage solutions provide ample space for all your belongings. The wardrobe includes a hanging rail, shelves, drawers, and a built-in coat rack.'),
(68, 'Modern Wardrobe with Integrated Shelving', 'WhatsApp Image 2024-10-04 at 10.05.35 AM (1).jpeg', 'Wardrobe', 'This spacious wardrobe features a modern design with a combination of gray and wood panels for a visually appealing look. The sliding doors save space and provide easy access to your clothing. The integrated shelving unit adds extra storage space for books, accessories, or decorative items. The wardrobe is perfect for organizing your belongings and keeping your bedroom clutter-free.'),
(69, 'Modern Sliding Door Wardrobe with Integrated Shelving', 'WhatsApp Image 2024-10-04 at 10.05.35 AM.jpeg', 'Wardrobe', 'This sleek and functional wardrobe features a modern design with sliding doors that save space and provide easy access to your clothing. The combination of light wood and gray panels adds a touch of visual interest. The integrated shelving unit provides extra storage space for books, accessories, or decorative items. The wardrobe is perfect for organizing your belongings and keeping your bedroom clutter-free.'),
(70, 'Modern Minimalist Wardrobe with Open Shelving', 'WhatsApp Image 2024-10-04 at 10.05.34 AM.jpeg', 'Wardrobe', 'This sleek and sophisticated wardrobe features a minimalist design with clean lines and a neutral gray finish. The open shelving unit adds a touch of visual interest and provides additional storage space for books, accessories, or decorative items. The wardrobe is perfect for organizing your belongings and keeping your bedroom clutter-free.'),
(71, 'Modern Mirrored Wardrobe with Sliding Doors', 'WhatsApp Image 2024-10-04 at 10.05.32 AM.jpeg', 'Wardrobe', 'This spacious and stylish wardrobe features a modern design with sliding doors that save space and provide easy access to your clothing. The combination of dark gray and light wood accents creates a visually appealing look. The wardrobe features mirrored doors that add a touch of elegance and functionality, allowing you to see your full outfit before leaving the house. The interior is thoughtfully designed with shelves, drawers, and hanging rods to accommodate all your belongings.'),
(72, 'Customizable Corner Walk-In Closet', 'WhatsApp Image 2024-10-04 at 10.05.31 AM.jpeg', 'Wardrobe', 'This spacious and customizable walk-in closet is designed to maximize storage space in a corner area. The shelves and drawers can be configured to suit your specific needs, allowing you to organize your clothing, accessories, and shoes efficiently. The open design provides easy access to all your belongings, while the neutral color palette creates a clean and modern look.'),
(73, 'Modern Walk-In Closet with Customizable Storage', 'WhatsApp Image 2024-10-04 at 10.05.30 AM.jpeg', 'Wardrobe', 'This spacious walk-in closet features a modern design with customizable storage options to suit your individual needs. The combination of open shelves and drawers provides ample space for organizing your clothing, accessories, and shoes. The neutral color palette creates a clean and inviting atmosphere.'),
(74, ' Spacious Sliding Door Wardrobe with Integrated Storage', 'WhatsApp Image 2024-10-04 at 10.05.29 AM (1).jpeg', 'Wardrobe', 'This large and functional wardrobe features sliding doors that save space and provide easy access to your clothing. The combination of dark wood and lighter accents creates a warm and inviting atmosphere. The interior is thoughtfully designed with shelves, drawers, hanging rods, and shoe compartments to accommodate all your belongings. The wardrobe is perfect for organizing your clothes and keeping your bedroom clutter-free.'),
(75, 'Modern Sliding Door Wardrobe with Customizable Interior', 'WhatsApp Image 2024-10-04 at 10.05.29 AM.jpeg', 'Wardrobe', 'This spacious and customizable wardrobe features sliding doors that save space and provide easy access to your clothing. The interior can be configured to suit your specific needs, allowing you to organize your belongings efficiently. The wardrobe includes shelves, drawers, hanging rods, and shoe compartments to accommodate all your clothing and accessories. The neutral color palette creates a clean and modern look.'),
(76, 'Modern Bedroom Suite with Integrated Dressing Table', 'WhatsApp Image 2024-10-04 at 10.05.28 AM (1).jpeg', 'Wardrobe', 'This stylish and functional bedroom suite combines a wardrobe with a built-in dressing table for a complete and cohesive look. The wardrobe features sliding doors that save space and provide easy access to your clothing. The dressing table is equipped with a mirror, drawers, and a vanity stool for a convenient and organized space. The combination of light wood and gray accents creates a warm and inviting atmosphere.'),
(77, 'Spacious Sliding Door Wardrobe with Customizable Interior', 'WhatsApp Image 2024-10-04 at 10.05.28 AM.jpeg', 'Wardrobe', 'This large and functional wardrobe features sliding doors that save space and provide easy access to your clothing. The interior can be customized to suit your specific needs, allowing you to organize your belongings efficiently. The wardrobe includes shelves, drawers, hanging rods, and shoe compartments to accommodate all your clothing and accessories. The neutral color palette creates a clean and modern look.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
